##-------Android--------
platformName=android
deviceName=25e4e5308f0d7ece
platformVersion=10
appPath=/Begenuin_28_8_2024.apk
automationName=UiAutomator2
server=http://127.0.0.1:4723/wd/hub
#appActivity=com.begenuin.auth.ui.activity.SplashActivity
#appPackage=com.google.android.packageinstaller
#-------iOS--------
#platformName = iOS
#server = http://0.0.0.0:4723/wd/hub
#deviceName = iPhone 11 - White
#udid = 00008030-0004192E228A802E
#updatedWDABundleId = com.datacz.WebDriverAgentLib
#platformVersion = 15.3.1
#automationName = XCUITest
#appPath = /Dataczar.ipa

browser=chrome
webURL=https://brands.qa.begenuin.com
userName = nayanankpal@begenuin.com
passWord = 123456
feURL= https://ankpal.qa.begenuin.com/home 
frontendUserName = nayanankpal@begenuin.com
frontendPassWord = 123456